### ISSUE TITLE
Feature Request: miscellaneous config stuff

### ISSUE THREAD

**Issue by A1eNaz** [xenia-manager/xenia-manager#102]
would like to see some of these options get added to the app.

gpu_allow_invalid_fetch_constants = true
**Fixes broken/transparency effects for games like MGS HD or FM4.**

use_fuzzy_alpha_epsilon = true
**Fixes fuzzy transparent effects for games like Tenchu Z.**

query_occlusion_fake_sample_count = -1
**Fixes lights clipping through walls in some games**
should be noted some games should stay with 1000 instead of -1 because it freezes if set to -1.
[for eg. MW2 or the GoW games.]

scribble_heap = true
disassemble_functions = true
**Alternative solutions to Readback_Resolve for some games.**
[Not every game works great with them like Most Wanted 2005 becoming more darker.]

widescreen = false
**For 4:3 aspect ratio.**
Resolutions below 1280x720 or 8 for `internal_display_resolution` should be noted they run at 4:3 aspect ratio.

custom_font_path = "font path here"
notification_sound_path = "wav file path here"
**For achievement notification.**

cl = "**command line for games gibberish stuff**"

launch_module = "xex file name here"
**For games that have multiple xex's like MGS HD**

--NETPLAY STUFF--
user_0_xuid = "XUID HERE"
user_1_xuid = "XUID HERE"
user_2_xuid = "XUID HERE"
user_3_xuid = "XUID HERE"
**[User's server-sde progress.]**

-- MOUSEHOOK STUFF IF IT GETS IMPLEMENTED --

invert_x = false
invert_y = true
sensitivity = 5.0
swap_wheel = true

**Comment by shazzaam7** [comment]
> custom_font_path = "font path here"
notification_sound_path = "wav file path here"
For achievement notification.

Achievements have currently a lot of issues and I'm planning on removing "Show Achievement notification" until they add proper achievement support. Example: Forza Horizon starts lagging when a notification happens.

> launch_module = "xex file name here"
For games that have multiple xex's like MGS HD

This option doesn't really work with --config. (Unless I'm using it the wrong way).

> --NETPLAY STUFF--
user_0_xuid = "XUID HERE"
user_1_xuid = "XUID HERE"
user_2_xuid = "XUID HERE"
user_3_xuid = "XUID HERE"
[User's server-sde progress.]

I won't add XUID since it's not supposed to be messed around with. Messing around with it is considered an advanced option in my book.

The rest of the options I'll most likely add, just I'm currently busy with XboxUnity integration.

**Comment by shazzaam7** [comment]
I have implemented `gpu_allow_invalid_fetch_constants`, `use_fuzzy_alpha_epsilon`, `query_occlusion_fake_sample_count` and `widescreen` in the latest [experimental build](https://github.com/xenia-manager/xenia-manager/releases/tag/experimental).

**Comment by A1eNaz** [comment]
forgot to include this:
max_signed_profiles = 4
limits how many controllers can be connected which can fix issues where multiple controllers are connected when not.
"Limits how many profiles can be assigned. Possible values: 1-4"
