### ISSUE TITLE
Check for new Xenia to additionally check currently installed version

### ISSUE THREAD

**Issue by markjfine** [xenia-manager/xenia-manager#118]
**Is your feature request related to a problem? Please describe.**
Currently, X-M checks the Xenia (or variant) release date from the API JSON against last checked date to determine if there's a new version. This does not take into account user's manual update (download or build) outside of X-M, potentially providing a false positive, therefore causing the update icon to show.

**Describe the solution you'd like**
`CheckForXeniaUpdates()` could conceivably check the version number of the currently installed copy of the Xenia variant against the first 9 characters (or so) of  the `target_commitish` tag in the JSON to determine if it's already been installed, and update `currentConfig.ReleaseDate` with `ReleaseDate` for the next call.

**Describe alternatives you've considered**
Unsure there are any alternatives, though at first blush this seems to be the most efficient method. It also assumes there's a way to extract the currently installed version number of Xenia. Number does not show when looking at file info via file explorer, though I seem to recall an OS-level method to do so.

**Additional context**
Realize this project is intended as a stopgap, but is mature enough to have a life of it's own. This is noted as a nice to have enhancement because of that.

**Comment by shazzaam7** [comment]
> Is your feature request related to a problem? Please describe.
Currently, X-M checks the Xenia (or variant) release date from the API JSON against last checked date to determine if there's a new version. This does not take into account user's manual update (download or build) outside of X-M, potentially providing a false positive, therefore causing the update icon to show.

Update icon is used to update Xenia Manager, not Xenia Emulator itself. 
When the Xenia Manager detects a new version of Xenia Emulator, it just shows the MessageBox saying what version got a new update and if you would like to update it or not (all happens in the background while you do something else).
The main reason why I use release date (`published_at` to be exact) is because it's the most consistent way of checking for updates (Xenia Canary only uses experimental tags for example).

**Comment by markjfine** [comment]
Heh. I assumed the clockwise arrow was for Xenia. My bad, I should have done a little more homework.

I'm also building X-M from the MSVS solution file and copying the published portions over to a runtime directory. In a sense this could apply to both Xenia and X-M, though my stated solution is only for Xenia itself.

It's a personal preference of mine to build things from github update pulls rather than just download them. Though as you say, I doubt the majority of your/Xenia users would be doing that. I just thought I'd throw the idea out there.

**Comment by shazzaam7** [comment]
I might add something to disable the auto updates for Xenia Manager if you're using experimental builds.
I'll reply to this issue if I add something like this.

Closing this issue.
