### ISSUE TITLE
Unable to change language and region

### ISSUE THREAD

**Issue by vikjITA** [xenia-manager/xenia-manager#128]
In settings, changing the language has no effect in game.
You should also add user_country features.

Starting Xenia directly and changing user_country to my language, the game starts in the correct language.

Starting the game via Xenia Manager the language remains unchanged in English.

Sorry for my bad English.

Thanks

Starting the game via Xenia Manager:
![Screenshot 2024-09-13 121058](https://github.com/user-attachments/assets/03f3c671-70a9-4ed9-a4d2-d7122cef424c)

Starting the game via Xenia directly:
![Screenshot 2024-09-13 121257](https://github.com/user-attachments/assets/6243143b-b657-4e48-9903-b318b4baac1a)

**Comment by shazzaam7** [comment]
I have a tooltip for `User Language` setting that says: "Used for changing language in games (If they support it)". I do allow you to open the game's configuration file in the Editor and change it yourself.
Because of this I won't label it as an issue, but I might add `user_country` option (It's not hard, just tedious because there are 109 countries according to the Xenia developer comments)
