### ISSUE TITLE
[Bug] app crashs when requesting for optimized settings if no game is selected 

### ISSUE THREAD

**Issue by VeraPhobia** [xenia-manager/xenia-manager#166]
## Describe the bug

choosing the option to "look up for the optimized settings..." if no game is selected crashes the app

## To Reproduce

open the app for the first time 
go to settings 
press the cloud icon for downloading the optimized settings

## Expected behavior
i feel a small pop up sating choose a game first would be a good way

## Environment Information

- OS: windows 11
- App Version: 2.0.0 experimental 

## Log File
[Log-20241011.txt](https://github.com/user-attachments/files/17345063/Log-20241011.txt)

## Additional context
while in a normal situation the user will have a game in their library before attempting to download a game prefix its a bug nevertheless, i could not see a way to change global settings in the new app but if it will be added in the future it will be a problem if the user accidentally press the cloud icon when in the global setting.

**Comment by shazzaam7** [comment]
Please for the future issues for v2.0.0 use the dedicated discussions.
I have disabled the global settings changing because of the way Xenia Manager v2.0.0 loads the configuration files (Symbolic Links instead of "--config" argument). Good reminder that I need to disable the access to settings if there are no installed games.

**Comment by VeraPhobia** [comment]
thanks for the fast reply :) 
and sorry didn't know there was a separate discussion for it and thanks for the great work
