### ISSUE TITLE
allow a way to change where the content folder goes 

### ISSUE THREAD

**Issue by 19Aidan** [xenia-manager/xenia-manager#44]
I have an PC that has multiple users. Unfortunately the manager has one shared content folder. I would like a way it uses my document folder instead storing the content folder in the xenia manager folder

**Comment by shazzaam7** [comment]
The reason why I made the Xenia Manager have everything in 1 folder is to make it as portable as possible. When deleting Xenia Manager, you just delete the folder and there you go, no leftovers.

I can recommend you to just have multiple Xenia Manager "installs" for now (Didn't properly test it, but should work without major issues since everything is portable). 

I might in the future add multiple profiles to Xenia Manager and use system links, but we'll see. If you have any questions, feel free to ask here.
