### ISSUE TITLE
For some reason I can't add PGR 3 in the list of the games

### ISSUE THREAD

**Issue by metalslayer** [xenia-manager/xenia-manager#50]
The only stuff Manager say is couldn't find it.
![2024-07-24_20-12-14](https://github.com/user-attachments/assets/c60ae41f-6898-4f3d-af20-582c4aa2ae4a)
![2024-07-24_20-13-21](https://github.com/user-attachments/assets/2549ae10-d913-4913-98fb-2ccc47de8046)

**Comment by shazzaam7** [comment]
First picture means that it just couldn't find the game in the lists of games and it asks you if you want to use the default icon (Pressing 'Yes') or if you want to search for the game yourself in the lists of games (Pressing 'No').

My guess is that you pressed the X button and now the manager can't find the game, ending in Library not loading, but you didn't provide enough information so I'm only guessing at this point.

For future please follow the bug report template, otherwise I will be forced to just close the issue.

**Comment by shazzaam7** [comment]
After checking game lists, PGR3 (Project Gotham Racing 3) is indeed in the lists and can be selected. Closing this issue now.
