### ISSUE TITLE
add more variants in options

### ISSUE THREAD

**Issue by artem45ik** [xenia-manager/xenia-manager#56]
In general settings you can add second license (-1 in xenia config file)
![Снимок экрана (518)](https://github.com/user-attachments/assets/bd256e8f-33aa-4737-bedf-1fcf054e2a74)
in display settings add more framelimit than 144 and safe area and I mean the ability to write the fps that you needed
![Снимок экрана (519)](https://github.com/user-attachments/assets/0babcb9e-889e-4ab5-944d-41bf13893431)

**Comment by shazzaam7** [comment]
License mask explanation: According to the [xenia wiki](https://github.com/xenia-canary/xenia-canary/wiki/Options#run-games-as-fullactivated), you can put it to EITHER -1 or 1.

Framerate limit explanation: I've put it to 144 because I think that's what most people have. For those who want higher framerate, you can use 'Open in Editor' option and put another value, although I doubt you will reach it.

**Comment by artem45ik** [comment]
Okay

**Comment by artem45ik** [comment]
and for some reason cache and scratch creates here
![Снимок экрана (520)](https://github.com/user-attachments/assets/abf5d227-6d58-4dc9-87a5-f44e01851c01)

**Comment by shazzaam7** [comment]
That's normal

**Comment by artem45ik** [comment]
> That's normal

later i changed it anyway
